[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ path = "./imgs", access = "read" }]

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
